### ISSUE TITLE
Improve Interface

### ISSUE THREAD

**Issue by ghost** [ArnavVarshney/CCSolutionsDownloader#3]
#### _I had 2 improvements in my mind. Would love to know your feedback!_

I think that if at the starting of this script
* If we can mention to the user that he should log out of his existing account in order to access this
Then that would be great!

* Also, we can mention that "CodeChef Username" means your own CC Username.

__Note__: _Please see attached image for reference_

![1](https://user-images.githubusercontent.com/54810697/89908809-fb794080-dc0b-11ea-9e83-2eda2c3dc179.JPG)

**Comment by ArnavVarshney** [comment]
I appreciate the feedback! A pull request would help speed things up and would be appreciated!

**Comment by ghost** [comment]
__Sure__, I will try to do that.
You can _assign it to me_!
